### ISSUE TITLE
NVRAM checksum insight??

### ISSUE THREAD

**Issue by SLKsander** [Fysac/orbicfg#2]
First, thank for a VERY helpful utility.  It has save a great deal of time.  THANK YOU.

My objective is to dump orbi config, use your utility to decrypt, sort and add things, then reencrypt and reload.   The major stumbling block at the moment is the checksum on the new NVRAM set.   Did you work uncover any info on how the checksum is generated by datalib?  Any help would be much appreciated.

**Comment by Fysac** [comment]
Hi,

I'm glad you found some use for this project. Unfortunately, I have not looked into the checksum generation part, but you raise a good point; this tool should support re-encryption of the NVRAM config. I may look into that this weekend (or sooner, if I have time).

**Comment by SLKsander** [comment]
Thanks, 
 
Scott

**Comment by Fysac** [comment]
An update: I've figured out how checksums are generated and have added code to _verify_ the checksum of a config backup: https://github.com/Fysac/orbicfg/blob/0b6ddd65d93c6dc4e7a333f4c451a7874e612284/main.c#L88

The code to smoothly re-encrypt and create a valid checksum for arbitrary NVRAM entries is going to take me a bit longer, but the core logic will simply be the reverse of the function linked above. For example:

```c
uint32_t create_checksum(unsigned char *data, size_t data_len) {
    uint32_t crc = 0xffffffff;
    for (int i = 0; i < data_len / sizeof(uint32_t); i++) {
        crc -= *((uint32_t *) data);
        data += sizeof(uint32_t);
    }
    return crc;
}
```

The `data` parameter refers to the plaintext/unencrypted key-value pairs, each separated by a null byte (`\0`). Note that in orbicfg's decryption output, [null bytes are replaced with newlines](https://github.com/Fysac/orbicfg/blob/0b6ddd65d93c6dc4e7a333f4c451a7874e612284/main.c#L77) for easier reading, so keep that in mind if you decide to implement your own encryption feature before me.

**Comment by SLKsander** [comment]
Thanks much.  I will take a look and let you know.
 
Thanks,
 
Scott

**Comment by Fysac** [comment]
Added in master branch.
