### ISSUE TITLE
RAX10 - AX1800

### ISSUE THREAD

**Issue by lshep5801** [Fysac/orbicfg#8]
FWIW, I tried this on a RAX10, although it is not supported, but still a NETGEAR.

Got the following error message: decrypt config: invalid checksum

Using the command: ./orbicfg -decrypt  NETGEAR_RAX10.cfg -out decrypt-RAX10.json

Using hexdump, it appears to me the magic number is not decoded in the file.  

From my attached file:
0000000 0425 2020 8e4c 0000 674d 0d61 a2ec 5c55
would imply the magic number is 20200425.

[NETGEAR_RAX10.zip](https://github.com/user-attachments/files/17401992/NETGEAR_RAX10.zip)

Not asking you to revise the program, but providing you additional information on different models and configs if this would be any use to you.

I used information provided in Closed Issue #6 to gather this information.

**Comment by Fysac** [comment]
Hi, can you share your firmware version?

**Comment by lshep5801** [comment]
Router Firmware Version V1.0.15.146Sent from my iPhoneOn Oct 20, 2024, at 11:26 AM, Fysac ***@***.***> wrote:﻿
Hi, can you share your firmware version?

**Comment by Fysac** [comment]
This was another case of an off-by-one magic value, so I added an override for it. It should work now if you pull 66bca7d.

At this rate, I might as well add some code to retry with stated magic + 1 whenever checksum validation fails :)

**Comment by lshep5801** [comment]
Thanks. Tested and works fine.
